
package me.moree.wsdl.mandiri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillPaymentServiceSoap", targetNamespace = "bankmandiri.h2h.billpayment.ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillPaymentServiceSoap {


    /**
     * 
     * @param request
     * @return
     *     returns me.moree.wsdl.mandiri.ReversalResponse
     */
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/reverse")
    @WebResult(name = "reverseResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "reverse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.Reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.ReverseResponse")
    public ReversalResponse reverse(
            @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
                    ReversalRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns me.moree.wsdl.mandiri.PaymentResponse
     */
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/payment")
    @WebResult(name = "paymentResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "payment", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.Payment")
    @ResponseWrapper(localName = "paymentResponseOut", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.PaymentResponseOut")
    public PaymentResponse payment(
            @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
                    PaymentRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns me.moree.wsdl.mandiri.InquiryResponse
     */
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/inquiry")
    @WebResult(name = "inquiryResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "inquiry", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.Inquiry")
    @ResponseWrapper(localName = "inquiryResponseOut", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.InquiryResponseOut")
    public InquiryResponse inquiry(
            @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
                    InquiryRequest request);

    /**
     * 
     * @param tx
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/echoTest")
    @WebResult(name = "echoTestResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "echoTest", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.EchoTest")
    @ResponseWrapper(localName = "echoTestResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "me.moree.wsdl.mandiri.EchoTestResponse")
    public String echoTest(
            @WebParam(name = "tx", targetNamespace = "bankmandiri.h2h.billpayment.ws")
                    String tx);

}
